### ISSUE TITLE
Lol password reset redirect url

### ISSUE THREAD

**Issue by heatherbooker** [dharness/slackchat-web#3]
http://localhost:3000/mailto:hello@kingofthestack.com?subject=Forgot%20Password&body=%0A%20%20%20%20%20%20Hey%20pal,%0A%0A%20%20%20%20%20%20I%20forgot%20my%20password%20for%20slackchat.%20I%20know,%20I%20know,%20I%20should%20have%20written%20it%20down.%0A%20%20%20%20%20%20But%20can%20you%20reset%20it%20for%20me?%0A%20%20%20%20%20%20My%20email%20address%20is%20YOUR_EMAIL_ADDRESS%0A%0A%20%20%20%20%20%20Sincerely,%0A%20%20%20%20%20%20A%20forgetful%20user%0A%20%20%20%20

**Comment by dharness** [comment]
This should open your mail, I feel like it used to... hm
