### ISSUE TITLE
Add signup page

### ISSUE THREAD

**Issue by heatherbooker** [dharness/slackchat-web#4]
![image](https://user-images.githubusercontent.com/12223751/33521578-9cbd1b12-d7a3-11e7-87d0-647c97b39781.png)
 Clicking this should send the user to a signup page where they give their information. This page needs to be created.

@dharness What info is needed to sign up?
- username
- password

Should this be a two step process - username/password, then they edit their profile/add info as convenient/needed?

**Comment by dharness** [comment]
Should be just username and password:

https://github.com/dharness/slackchat-api/blob/master/server.js#L37
https://github.com/dharness/slackchat-api/blob/master/config/passport.js#L19
